version: '3.8'

services:
  app:
    image: saurer-siggi-inventory-manager:latest
    container_name: saurer-siggi-inventory-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
      - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
    env_file:
      - .env
