version: '3.8'

services:
  app:
    image: ghcr.io/Saurer-Siggi/inventory-manager:latest
    container_name: saurer-siggi-inventory-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
